# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.finance::lang.models.receipt.label'

# Model Form Field configuration
form: $/acorn/finance/models/receipt/fields.yaml

# Model Class name
modelClass: Acorn\Finance\Models\Receipt

# Default redirect location
defaultRedirect: acorn/finance/receipts

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/finance/receipts/update/:id
    redirectClose: acorn/finance/receipts

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/finance/receipts
    redirectClose: acorn/finance/receipts

# Preview page
preview:
    title: backend::lang.form.preview_title
