ALTER TABLE IF EXISTS ONLY public.acorn_finance_receipts DROP CONSTRAINT IF EXISTS purchase_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_payments DROP CONSTRAINT IF EXISTS invoice_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_receipts DROP CONSTRAINT IF EXISTS currency_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_purchases DROP CONSTRAINT IF EXISTS currency_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_payments DROP CONSTRAINT IF EXISTS currency_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_invoices DROP CONSTRAINT IF EXISTS currency_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_receipts DROP CONSTRAINT IF EXISTS backend_user_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_payments DROP CONSTRAINT IF EXISTS backend_user_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_invoices DROP CONSTRAINT IF EXISTS backend_user_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_purchases DROP CONSTRAINT IF EXISTS backend_user_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_receipts DROP CONSTRAINT IF EXISTS backend_user_group_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_payments DROP CONSTRAINT IF EXISTS backend_user_group_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_invoices DROP CONSTRAINT IF EXISTS backend_user_group_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_purchases DROP CONSTRAINT IF EXISTS backend_user_group_id;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_receipts DROP CONSTRAINT IF EXISTS acorn_finance_receipts_pkey;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_purchases DROP CONSTRAINT IF EXISTS acorn_finance_purchases_pkey;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_payments DROP CONSTRAINT IF EXISTS acorn_finance_payments_pkey;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_invoices DROP CONSTRAINT IF EXISTS acorn_finance_invoices_pkey;
ALTER TABLE IF EXISTS ONLY public.acorn_finance_currencies DROP CONSTRAINT IF EXISTS acorn_finance_currency_pkey;
DROP INDEX IF EXISTS public.fki_currency_id;
DROP INDEX IF EXISTS public.fki_backend_user_id;
DROP INDEX IF EXISTS public.fki_backend_user_group_id;
DROP TABLE IF EXISTS public.acorn_finance_receipts;
DROP TABLE IF EXISTS public.acorn_finance_purchases;
DROP TABLE IF EXISTS public.acorn_finance_payments;
DROP TABLE IF EXISTS public.acorn_finance_invoices;
DROP TABLE IF EXISTS public.acorn_finance_currencies;
